spring.profiles: heroku
server:
  port: "${PORT}"
spring:
  datasource:
    url: "${JDBC_DATABASE_URL}"
    username: "${JDBC_DATABASE_USERNAME}"
    password: "${JDBC_DATABASE_PASSWORD}"
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 3
    initialSize: 5
    removeAbandoned: true
spring.h2.console.enabled: false
